"""add message role constraint

Revision ID: 594438747399
Revises: 64c3c1fbeccb
Create Date: 2026-09-19 22:05:12.843533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594438747399'
down_revision: Union[str, Sequence[str], None] = '64c3c1fbeccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_messages_role",
        "messages",
        "role IN ('user', 'assistant')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_messages_role",
        "messages",
        type_="check"
    )
    # ### end Alembic commands ###
